api_platform:
    title: Defi Fullstack
    use_symfony_listeners: true
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Route/UI/Http/Rest/'
            - '%kernel.project_dir%/src/Security/UI/Http/Rest/'
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
