tls:
  certificates:
    - certFile: /certs/wildcard.defifullstack.com.crt
      keyFile: /certs/wildcard.defifullstack.com.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/wildcard.defifullstack.com.crt
        keyFile: /certs/wildcard.defifullstack.com.key